// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtSE6Wdt1sHoizCJiiyV1Nf0Z7VGa6xSY',
    appId: '1:866184039578:android:1d98bc9a8f4295782fa323',
    messagingSenderId: '866184039578',
    projectId: 'flutteross',
    storageBucket: 'flutteross.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBbLQdcUGNo9MxpVqIxICuuOMRRkeyDGg',
    appId: '1:866184039578:web:9a3a2a5875a0e5d22fa323',
    messagingSenderId: '866184039578',
    projectId: 'flutteross',
    authDomain: 'flutteross.firebaseapp.com',
    storageBucket: 'flutteross.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBbLQdcUGNo9MxpVqIxICuuOMRRkeyDGg',
    appId: '1:866184039578:web:1160ec2ab352c16f2fa323',
    messagingSenderId: '866184039578',
    projectId: 'flutteross',
    authDomain: 'flutteross.firebaseapp.com',
    storageBucket: 'flutteross.firebasestorage.app',
  );

}